services:
  - type: web
    name: spotifaibot
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun install --frozen-lockfile && bun run build && bun run migrate
    startCommand: bun serve
    buildFilter:
      ignoredPaths:
        - suno-app/**/*.ts
        - suno/*.json
    envVars:
      - fromGroup: spotifaibot
      - key: DATABASE_URL
        fromDatabase:
          name: spotifai
          property: connectionString
      - key: APP_URL
        value: https://bot.spotifai.grambot.fun
    domains:
      - "v1.api.spotifai.grambot.fun"
  - type: web
    name: spotifai
    runtime: static
    autoDeploy: true
    buildCommand: cd suno-app && bun install --frozen-lockfile && bun run build
    staticPublishPath: suno-app/dist
    buildFilter:
      paths:
        - suno-app/**/*.ts
        - suno/*.json
    envVars:
      - fromGroup: spotifai
      - key: VITE_APP_API_BASE_URL
        value: https://v1.api.spotifai.grambot.fun
    domains:
      - bot.spotifai.grambot.fun
databases:
  - name: spotifai
    databaseName: spotifai
    user: admin
