services:
  - type: web
    name: museaibot
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun install --frozen-lockfile
    startCommand: bun start
    envVars:
      - fromGroup: museaibot
      - key: DATABASE_URL
        fromDatabase:
          name: museai
          property: connectionString
    domains:
      - "api.museaibot.com"
databases:
  - name: museai
    databaseName: museai
    user: admin
    plan: starter
