services:
  - type: web
    name: museaibot
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: bun install --frozen-lockfile && bun run build && bun run migrate
    startCommand: bun serve
    envVars:
      - fromGroup: museaibot
      - key: DATABASE_URL
        fromDatabase:
          name: museai
          property: connectionString
      - key: APP_URL
        value: https://bot.museai.grambot.fun
    domains:
      - "v1.api.museai.grambot.fun"
  - type: web
    name: museai
    runtime: static
    autoDeploy: true
    buildCommand: cd suno-app && bun install --frozen-lockfile && bun run build
    staticPublishPath: suno-app/dist
    envVars:
      - fromGroup: museai
      - key: VITE_APP_API_BASE_URL
        value: https://v1.api.museai.grambot.fun
    domains:
      - bot.museai.grambot.fun
databases:
  - name: museai
    databaseName: museai
    user: admin
