services:
   - type: web
     name: museaibot
     runtime: node
     plan: starter
     autoDeploy: true
     buildCommand: pnpm build
     startCommand:  pnpm serve
     envVars:
       - fromGroup: museaibot
     domains:
       - "api.museaibot.com"
databases:
  - name: museai 
    databaseName: museai
    user: admin
    plan: free 
